### ISSUE TITLE
Application crash on macOS

### ISSUE THREAD

**Issue by aarant** [arantonitis/soar#5]
Due to a bugged version of Tk present on Macs, Soar will crash whenever started in GUI mode. Mac users will have to manually install a version of Tcl/Tk. See [this link](https://www.python.org/download/mac/tcltk/).

**Comment by jodalyst** [comment]
Fix it by changing your matplotlib config...

Create a file inside ~/.matplotlib called matplotlibrc that contains the line:

```
backend: TkAgg
```

Should be all set.  Tested on two macs (also this is why mine worked...I forgot I did this 1.5 years ago :/ )


I added instructions to course website

**Comment by aarant** [comment]
@jodalyst Is it possible to do this in Soar's PlotWindow itself? I believe CMax did something similar--something like:
```
import matplotlib
matplotlib.use('TkAgg')
```
which selects the backend to use according to [this](https://matplotlib.org/faq/usage_faq.html).

Can't confirm whether this will eliminate the need to change the config as I don't have access to a Mac.

**Comment by jodalyst** [comment]
Yes that *should* work as well...I'm not sure the implications of doing that on things other than Mac, though so maybe something like

```
import matplotlib
import platform
if 'Darwin' in platform.system():
    matplotlib.use('Tkagg')

```
to be safe...?

**Comment by aarant** [comment]
@jodalyst I'll add the change in the release that'll be pushed tonight, if it works I can close this issue.

**Comment by aarant** [comment]
Tested on El Capitan, selecting the Tk backend works and prevents a crash.
